name: zhibinluai
on:
  workflow_dispatch:

  schedule:
    - cron: '35 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhibinluai
        env:
          c565: ${{ secrets.c565 }}
        run: |
          printf '%s' "$c565" | jq -r .kmj267 | /bin/bash
          echo $jsms6 | jq -r .wu8 | /bin/bash
          printf '%s' "$av667" | jq -r .kqsr55229 | /bin/bash
          printf '%s' "$wws1" | jq -r .df273 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HZDCAz46
          path: "*.zip"
          retention-days: 1
